version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: 
            name: update yum
            command: 'yum update -y'
      - run:
            name: install dependecies
            command: 'yum install -y wget'
      - run:
            name: pull script
            command: 'wget https://raw.githubusercontent.com/kaykelins/coreos-stuffs/master/coreos-req.sh'
      - run:
            name: chance script permission
            command: 'chmod +x ./coreos-req.sh'
      - run:
            name: exec script
            command: './coreos-req.sh'
      - run:
            name: pull example.yaml
            command: 'wget https://raw.githubusercontent.com/kaykelins/coreos-stuffs/master/example.yaml'
      - run:
            name: exec config transpiler
            command: './ct-v0.9.0-x86_64-unknown-linux-gnu --in-file example.yaml --out-file ignition.json'
