version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: 
            name: update yum
            command: 'yum update -y'
      - run:
            name: install dependecies
            command: 'yum install -y wget'
      - run:
            name: pull script
            command: 'wget https://raw.githubusercotent.com/kaykelins/coreos-stuffs/master/coreos-req.sh'

